name: my-alternatives
dependencies:
  - python>=3.7
  - pip==20.1.1
  - flask==1.1.2
  - numpy==1.18.5
  - pandas==1.1.2
  - notebook==6.1.3
  - ipywidgets==7.5.1
  - matplotlib==3.3.1
  - seaborn==0.11.0
  - pip:
        - -r file:requirements.txt